# Generated by Django 6.0.1 on 2026-02-04 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('deposit', models.BooleanField()),
                ('for_students', models.BooleanField()),
                ('for_workers', models.BooleanField()),
                ('smoking_allowed', models.BooleanField()),
                ('pets_allowed', models.BooleanField()),
            ],
            options={
                'db_table': 'terms',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('story_count', models.PositiveIntegerField()),
                ('elevator', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('garage', models.BooleanField()),
                ('cctv', models.BooleanField()),
                ('intercom', models.BooleanField()),
                ('room_count', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('story', models.PositiveIntegerField()),
                ('condition', models.CharField(max_length=255)),
                ('heating', models.CharField(max_length=255)),
                ('furnishings', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, to='listings.item')),
                ('poster', models.ForeignKey(db_column='poster_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='listing_saves', to=settings.AUTH_USER_MODEL)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.terms')),
            ],
            options={
                'db_table': 'listing',
            },
        ),
    ]
